@echo off
REM ========================================
REM Quick Fix - Use SQLite (No Setup Needed)
REM ========================================

echo.
echo ========================================
echo   Quick Fix - SQLite Database
echo ========================================
echo.
echo This will set up a local SQLite database
echo No external database required!
echo.

REM Create .env.local with SQLite
echo [STEP 1/5] Creating .env.local with SQLite...
(
echo # DigitalMEng - Local Development Configuration
echo # Auto-generated by fix-all-errors-sqlite.bat
echo.
echo # Database - SQLite (No setup required^)
echo DATABASE_URL="file:./dev.db"
echo.
echo # Authentication
echo NEXTAUTH_URL=http://localhost:3000
echo NEXTAUTH_SECRET=dev-secret-change-in-production-min-32-chars-required
echo JWT_SECRET=dev-jwt-secret-change-in-production-minimum-32-characters
echo.
echo # Application
echo NEXT_PUBLIC_APP_URL=http://localhost:3000
echo NEXT_PUBLIC_APP_NAME=DigitalMEng
echo NODE_ENV=development
echo DEMO_MODE=true
echo.
echo # Session
echo SESSION_COOKIE_NAME=session_token
echo SESSION_MAX_AGE=604800
) > .env.local

echo [OK] .env.local created with SQLite configuration
echo.

echo [STEP 2/5] Installing dependencies...
call npm install
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to install dependencies
    pause
    exit /b 1
)
echo [OK] Dependencies installed
echo.

echo [STEP 3/5] Generating Prisma Client...
call npm run db:generate
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to generate Prisma client
    echo.
    echo Trying alternative method...
    call npx prisma generate
    if %ERRORLEVEL% NEQ 0 (
        echo [ERROR] Still failed. Check the error above.
        pause
        exit /b 1
    )
)
echo [OK] Prisma client generated
echo.

echo [STEP 4/5] Creating database and tables...
call npm run db:push
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to create database
    echo.
    echo Trying alternative method...
    call npx prisma db push
    if %ERRORLEVEL% NEQ 0 (
        echo [ERROR] Still failed. Check the error above.
        pause
        exit /b 1
    )
)
echo [OK] Database created successfully
echo.

echo [STEP 5/5] Creating admin user...
call npm run admin:quick
if %ERRORLEVEL% NEQ 0 (
    echo [WARNING] Admin creation failed
    echo You can create it manually later with: npm run admin:quick
) else (
    echo [OK] Admin user created
)
echo.

echo ========================================
echo   SUCCESS! All Errors Fixed!
echo ========================================
echo.
echo Database: SQLite (file: ./dev.db^)
echo.
echo Login at: http://localhost:3000/login
echo   Email: admin@digitalmeng.com
echo   Password: admin123
echo.
echo IMPORTANT: Change password after first login!
echo.
echo Your dev server should already be running.
echo If not, start it with: npm run dev
echo.
pause
