@echo off
REM ========================================
REM MySQL Installation Guide for Windows
REM ========================================

echo.
echo ========================================
echo   MySQL Installation for DigitalMEng
echo ========================================
echo.

REM Check if MySQL is already installed
where mysql >nul 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [INFO] MySQL is already installed!
    echo.
    mysql --version
    echo.
    goto :setup_database
)

echo [STEP 1] MySQL is not installed. Let's install it!
echo.
echo Opening MySQL download page...
echo.
echo Please follow these steps:
echo   1. Download MySQL Installer from the browser window
echo   2. Choose "mysql-installer-community" (Windows MSI Installer)
echo   3. Run the installer
echo   4. Select "Developer Default" setup type
echo   5. Set a ROOT PASSWORD (remember this!)
echo   6. Complete the installation
echo   7. Come back here and press any key
echo.

start https://dev.mysql.com/downloads/installer/

pause

echo.
echo Checking if MySQL was installed...
where mysql >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] MySQL not found in PATH
    echo.
    echo Please ensure MySQL is installed and added to PATH
    echo Default location: C:\Program Files\MySQL\MySQL Server 8.0\bin
    echo.
    echo Add to PATH:
    echo   1. Search "Environment Variables" in Windows
    echo   2. Edit "Path" variable
    echo   3. Add: C:\Program Files\MySQL\MySQL Server 8.0\bin
    echo   4. Restart this script
    echo.
    pause
    exit /b 1
)

echo [OK] MySQL installed successfully!
echo.

:setup_database
echo.
echo ========================================
echo   Database Setup
echo ========================================
echo.

REM Get MySQL root password
set /p MYSQL_PASSWORD="Enter MySQL root password: "

echo.
echo [STEP 2] Creating database 'digitalmeng'...
echo.

REM Create database
mysql -u root -p%MYSQL_PASSWORD% -e "CREATE DATABASE IF NOT EXISTS digitalmeng;" 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to create database
    echo Please check your password and try again
    echo.
    echo Manual steps:
    echo   1. Open Command Prompt
    echo   2. Run: mysql -u root -p
    echo   3. Enter password
    echo   4. Run: CREATE DATABASE digitalmeng;
    echo   5. Run: EXIT;
    echo.
    pause
    exit /b 1
)

echo [OK] Database 'digitalmeng' created!
echo.

echo [STEP 3] Creating dedicated user (optional but recommended)...
echo.

set /p CREATE_USER="Create dedicated user 'digitalmeng'? (y/n): "
if /i "%CREATE_USER%"=="y" (
    set /p DB_PASSWORD="Enter password for 'digitalmeng' user: "
    
    mysql -u root -p%MYSQL_PASSWORD% -e "CREATE USER IF NOT EXISTS 'digitalmeng'@'localhost' IDENTIFIED BY '%DB_PASSWORD%';" 2>nul
    mysql -u root -p%MYSQL_PASSWORD% -e "GRANT ALL PRIVILEGES ON digitalmeng.* TO 'digitalmeng'@'localhost';" 2>nul
    mysql -u root -p%MYSQL_PASSWORD% -e "FLUSH PRIVILEGES;" 2>nul
    
    echo [OK] User 'digitalmeng' created with full privileges
    echo.
    
    set DB_USER=digitalmeng
    set DB_PASS=%DB_PASSWORD%
) else (
    set DB_USER=root
    set DB_PASS=%MYSQL_PASSWORD%
)

echo [STEP 4] Creating .env.local configuration...
echo.

REM Create .env.local
(
echo # DigitalMEng - MySQL Local Configuration
echo # Auto-generated by MySQL installation script
echo.
echo # MySQL Database Connection
echo DATABASE_URL="mysql://%DB_USER%:%DB_PASS%@localhost:3306/digitalmeng"
echo.
echo # Authentication
echo NEXTAUTH_URL=http://localhost:3000
echo NEXTAUTH_SECRET=dev-secret-change-in-production-min-32-chars-required
echo JWT_SECRET=dev-jwt-secret-change-in-production-minimum-32-chars
echo.
echo # Application
echo NEXT_PUBLIC_APP_URL=http://localhost:3000
echo NEXT_PUBLIC_APP_NAME=DigitalMEng
echo NODE_ENV=development
echo DEMO_MODE=true
echo.
echo # Session
echo SESSION_COOKIE_NAME=session_token
echo SESSION_MAX_AGE=604800
) > .env.local

echo [OK] .env.local created with MySQL configuration
echo.

echo [STEP 5] Testing MySQL connection...
echo.

mysql -u %DB_USER% -p%DB_PASS% -e "USE digitalmeng; SELECT 'Connection successful!' as Status;" 2>nul
if %ERRORLEVEL% EQU 0 (
    echo [OK] MySQL connection successful!
) else (
    echo [WARNING] Could not verify connection
)
echo.

echo [STEP 6] Installing Node.js dependencies...
echo.
call npm install
echo.

echo [STEP 7] Generating Prisma Client for MySQL...
echo.
call npm run db:generate
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to generate Prisma client
    pause
    exit /b 1
)
echo.

echo [STEP 8] Creating database tables...
echo.
call npm run db:push
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Failed to create tables
    echo Check the error above
    pause
    exit /b 1
)
echo.

echo [STEP 9] Creating admin user...
echo.
call npm run admin:quick
echo.

echo ========================================
echo   INSTALLATION COMPLETE!
echo ========================================
echo.
echo MySQL Database: digitalmeng
echo User: %DB_USER%
echo Host: localhost:3306
echo.
echo Admin Login:
echo   URL: http://localhost:3000/login
echo   Email: admin@digitalmeng.com
echo   Password: admin123
echo.
echo IMPORTANT: Change admin password after first login!
echo.
echo Your dev server should be running at:
echo   http://localhost:3000
echo.
echo To view database:
echo   npm run db:studio
echo.
echo To access MySQL directly:
echo   mysql -u %DB_USER% -p
echo.
pause
